import sqlite3
import os

DB_PATH = "events.db"

WEEKEND_EVENTS_DATA = [
    {
        "item_type": "event",
        "title": "静岡秋まつり 駿府城ナイトフェス 2026",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 15:00〜21:00",
        "location": "駿府城公園 中堀・天守台跡周辺",
        "city": "静岡市",
        "address": "静岡県静岡市葵区駿府城公園1-1",
        "lat": 34.9792,
        "lng": 138.3833,
        "google_maps_url": "https://maps.google.com/?q=34.9792,138.3833",
        "official_url": "https://sumpu-castlepark.com/",
        "tags": "秋まつり, 今週末, ナイトイベント, 屋台, 駿府城",
        "summary": "駿府城公園のライトアップとともに、静岡ご当地グルメ屋台や竹あかりの幻想的な空間を楽しめる今週末限定の秋フェス。",
        "description": "駿府城公園の歴史的景観を活かした秋のナイトフェスティバル。県内各地の人気クラフトビールや静岡おでん、富士宮やきそば等のグルメ屋台が多数出店。和楽器ライブやプロジェクションマッピング演出も開催されます。",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料（飲食有料）",
        "organizer": "静岡秋まつり実行委員会",
        "parking_info": "市民文化会館・周辺有料駐車場をご利用ください",
        "target_age": "全年齢（ファミリー・カップル・シニア）",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "ファミリー向け,カップル向け"
    },
    {
        "item_type": "event",
        "title": "浜松クラフトビール＆オータムグルメフェスティバル 2026",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 11:00〜20:00",
        "location": "浜松城公園 葵広場",
        "city": "浜松市",
        "address": "静岡県浜松市中央区葵町",
        "lat": 34.7111,
        "lng": 137.7247,
        "google_maps_url": "https://maps.google.com/?q=34.7111,137.7247",
        "official_url": "https://www.entetsu.co.jp/",
        "tags": "クラフトビール, 今週末, グルメ, 浜松城, 音楽",
        "summary": "国内外のブルワリー30社以上が集結！浜松城の緑に囲まれて最高の一杯と限定フードを堪能。",
        "description": "浜松城公園の開放的な広場で開催される秋のクラフトビール祭り。浜松餃子や地元産ソーセージなどの絶品ペアリングフードが勢揃い。アコースティックライブの心地よい音色とともに秋の週末を過せます。",
        "image_url": "https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料（ビールグラス・飲食チケット別）",
        "organizer": "浜松クラフトビールフェス実行委員会",
        "parking_info": "浜松城公園駐車場（有料）または公共交通機関",
        "target_age": "大人・カップル向け",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "沼津港 海鮮うまいもの市＆秋まつり",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 9:00〜16:00",
        "location": "沼津港 魚市場周辺特設会場",
        "city": "沼津市",
        "address": "静岡県沼津市千本港町128-1",
        "lat": 35.0805,
        "lng": 138.8572,
        "google_maps_url": "https://maps.google.com/?q=35.0805,138.8572",
        "official_url": "https://numazukou.com/",
        "tags": "海鮮, 今週末, 沼津港, 競り体験, 家族向け",
        "summary": "駿河湾の新鮮な海の幸が市場価格で大奉仕！大迫力のマグロ解体ショーや子供向け競り体験も開催。",
        "description": "沼津港の味覚が一同に集結する週末感謝イベント。その日の朝競り落とされた鮮魚の即売会、名物深海魚スープの無料振る舞い（各日先着200名）、小学生以下限定の模擬競り体験など、家族みんなで楽しめます。",
        "image_url": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "沼津港振興会",
        "parking_info": "沼津港大型展望水門びゅうお駐車場（無料）あり",
        "target_age": "全年齢（ファミリー大歓迎）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "ファミリー向け,雨の日OK"
    },
    {
        "item_type": "event",
        "title": "熱海サンビーチ 秋のナイトキャンドルフェスティバル",
        "date_str": "2026年9月12日(土) 18:00〜21:00",
        "location": "熱海サンビーチ ムーンテラス周辺",
        "city": "熱海市",
        "address": "静岡県熱海市東海岸町",
        "lat": 35.0964,
        "lng": 139.0768,
        "google_maps_url": "https://maps.google.com/?q=35.0964,139.0768",
        "official_url": "https://www.ataminews.gr.jp/",
        "tags": "キャンドル, 今週末, ロマンチック, ナイトイベント, デート",
        "summary": "3,000個のキャンドルが熱海サンビーチを優しく照らす、秋の夜限定のロマンチックイベント。",
        "description": "波音と潮風が心地よい熱海サンビーチのムーンテラスにて、3,000個以上のLED＆グラスキャンドルが点灯。キャンドルアートの背景には夜の海と温泉街の明かりが広がり、カップルや旅の思い出作りに最適です。",
        "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
        "fee": "観覧無料",
        "organizer": "熱海市観光協会",
        "parking_info": "市営東駐車場（有料）徒歩2分",
        "target_age": "大人・カップル推奨",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け"
    },
    {
        "item_type": "event",
        "title": "伊豆高原 アート＆ハンドメイドクラフトフェア",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 10:00〜16:00",
        "location": "伊豆高原 桜並木通り・特設会場",
        "city": "伊東市",
        "address": "静岡県伊東市八幡野",
        "lat": 34.8789,
        "lng": 139.1089,
        "google_maps_url": "https://maps.google.com/?q=34.8789,139.1089",
        "official_url": "https://izukougen-art.org/",
        "tags": "ハンドメイド, 今週末, クラフト, 伊豆高原",
        "summary": "全国から100名の作家が集まる木工・陶芸・ガラス細工のクラフト市。限定ワークショップも開催。",
        "description": "緑豊かな伊豆高原で開催される人気クラフト市。オリジナルの革製品、アクセサリー、木工家具などの展示販売が行われ、作家との対話を楽しみながらお気に入りの1点を探せます。カフェブースも多数出店。",
        "image_url": "https://images.unsplash.com/photo-1459908676235-d5f02a50184b?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "伊豆高原アートフェスティバル実行委員会",
        "parking_info": "伊豆高原駅周辺駐車場（有料）ご利用",
        "target_age": "全年齢（カップル・ファミリー）",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "富士山麓 ご当地グルメ＆キッズフェスタ 2026",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 10:00〜16:30",
        "location": "富士山樹空の森 大芝生広場",
        "city": "御殿場市",
        "address": "静岡県御殿場市印野1380-15",
        "lat": 35.2891,
        "lng": 138.8689,
        "google_maps_url": "https://maps.google.com/?q=35.2891,138.8689",
        "official_url": "http://jukuu.or.jp/",
        "tags": "富士山, 今週末, キッズ, 体験, ふわふわ遊具",
        "summary": "雄大な富士山をバックに、大型エア遊具やはたらく車が大集合！親子で一日中遊び尽くせる体感イベント。",
        "description": "富士山樹空の森の広大な大芝生広場で開催されるファミリーイベント。巨大滑り台やふわふわ遊具、高所作業車搭乗体験、キッズ職業体験などアトラクション満載。ご当地キッチンカー20店舗が集結。",
        "image_url": "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料（一部有料アトラクションあり）",
        "organizer": "富士山樹空の森",
        "parking_info": "無料駐車場 500台完備",
        "target_age": "未就学児〜小学生ファミリー中心",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "掛川城 秋の特別夜間開園＆ライトアップ",
        "date_str": "2026年9月12日(土) 18:00〜20:30",
        "location": "掛川城天守閣・本丸広場",
        "city": "掛川市",
        "address": "静岡県掛川市掛川1138-24",
        "lat": 34.7753,
        "lng": 138.0146,
        "google_maps_url": "https://maps.google.com/?q=34.7753,138.0146",
        "official_url": "https://kakegawajo.com/",
        "tags": "掛川城, 今週末, ライトアップ, 歴史, 夜景",
        "summary": "木造復元天守が秋の夜空に浮かび上がる今週末限定の夜間開園。本丸広場では和太鼓演奏も。",
        "description": "普段は見られない夜間の掛川城天守閣に入館できる限定イベント。ライトアップされた木造天守からの城下町の夜景は絶景。本丸広場では地元保存会による勇壮な和太鼓演奏が披露されます。",
        "image_url": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
        "fee": "天守閣入館料 大人410円 / 小中学生150円",
        "organizer": "掛川城公園管理事務所",
        "parking_info": "大手門駐車場（有料）ご利用",
        "target_age": "全年齢（歴史ファン・カップル）",
        "is_free_parking": 0,
        "is_stroller_ok": 0,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "焼津さかなセンター 秋の大感謝祭マルシェ",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 9:00〜17:00",
        "location": "焼津さかなセンター イベント広場",
        "city": "焼津市",
        "address": "静岡県焼津市八楠4-13-7",
        "lat": 34.8845,
        "lng": 138.3123,
        "google_maps_url": "https://maps.google.com/?q=34.8845,138.3123",
        "official_url": "https://www.sakana-center.com/",
        "tags": "焼津, 今週末, 海鮮, マグロ, 屋内マルシェ",
        "summary": "南マグロや焼津名物黒はんぺんの特別即売！豪華景品が当たる大ガラポン抽選会も開催。",
        "description": "東名焼津ICすぐの巨大水産市場で開催される秋の感謝感謝祭。市場内各店による大特価市に加え、焼津の鰹節削り体験、新鮮な生マグロの試食会を実施。雨の日でも全天候型アーケードで快適です。",
        "image_url": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "焼津さかなセンター組合",
        "parking_info": "大型無料駐車場 600台完備",
        "target_age": "全年齢（全天候・ベビーカー可）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "ファミリー向け,雨の日OK"
    },
    {
        "item_type": "event",
        "title": "磐田市民文化会館 ジュビロ秋のファンフェスタ 2026",
        "date_str": "2026年9月13日(日) 10:00〜16:00",
        "location": "磐田市民文化会館 かたりあ＆屋外広場",
        "city": "磐田市",
        "address": "静岡県磐田市上新屋678-1",
        "lat": 34.7345,
        "lng": 137.8567,
        "google_maps_url": "https://maps.google.com/?q=34.7345,137.8567",
        "official_url": "https://www.jubilo-iwata.co.jp/",
        "tags": "ジュビロ磐田, 今週末, スポーツ, ステージ, キッズ",
        "summary": "ジュビロ磐田公式イベント！マスコットキャラクターショーやミニサッカーアトラクション。",
        "description": "ジュビロ磐田ファンと地域住民のための秋のファン感謝イベント。特設ステージでのパフォーマンス、マスコット「ジュビロくん＆ジュビィちゃん」との写真撮影会、限定グッズマルシェが開催されます。",
        "image_url": "https://images.unsplash.com/photo-1508997449629-303059a039c0?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "ジュビロ磐田ホームタウン推進協議会",
        "parking_info": "施設無料駐車場 350台完備",
        "target_age": "全年齢（子育て家族大歓迎）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "ファミリー向け,雨の日OK"
    },
    {
        "item_type": "event",
        "title": "三嶋大社 秋の骨董市＆ハンドメイドマルシェ",
        "date_str": "2026年9月13日(日) 8:00〜15:00",
        "location": "三嶋大社 境内・参道",
        "city": "三島市",
        "address": "静岡県三島市大宮町2-1-5",
        "lat": 35.1225,
        "lng": 138.9189,
        "google_maps_url": "https://maps.google.com/?q=35.1225,138.9189",
        "official_url": "http://mishimataisya.or.jp/",
        "tags": "三嶋大社, 今週末, 骨董市, アンティーク, 神社散策",
        "summary": "伊豆一の宮の歴史ある境内におしゃれな古道具やアンティーク、てづくり雑貨店が集結。",
        "description": "三嶋大社の参道沿いで開催される月1回の人気市。全国の骨董商によるアンティーク家具・着物・陶磁器から、地元のクラフト作家のハンドメイド作品まで約60店が並びます。参拝と合わせて散策を楽しめます。",
        "image_url": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "三島骨董市実行委員会",
        "parking_info": "三嶋大社有料駐車場または周辺コインパーキング",
        "target_age": "全年齢（シニア・カップル）",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "清水港 帆船見学フェスタ 2026",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 9:30〜16:00",
        "location": "清水港 日の出ふ頭",
        "city": "静岡市",
        "address": "静岡県静岡市清水区日の出町10-80",
        "lat": 35.0112,
        "lng": 138.4923,
        "google_maps_url": "https://maps.google.com/?q=35.0112,138.4923",
        "official_url": "https://www.dream-plaza.co.jp/",
        "tags": "清水港, 今週末, 帆船, 甲板公開, 富士山 view",
        "summary": "大型帆船が清水港に寄港！迫力のセイルドリル（展帆作業）や一般甲板公開を実施。",
        "description": "富士山を望む清水港日の出ふ頭に美しい帆船が寄港。普段は入ることのできない船内の甲板一般公開や、実演セイルドリル、船長衣装での記念撮影コーナーを実施。エスパルスドリームプラザに隣接しています。",
        "image_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
        "fee": "見学無料",
        "organizer": "清水港振興協会",
        "parking_info": "ドリプラ駐車場（有料・施設利用割引あり）",
        "target_age": "全年齢（キッズ・写真好き）",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "ファミリー向け,カップル向け"
    },
    {
        "item_type": "event",
        "title": "藤枝 蓮華寺池公園 ナイトピクニック＆ジャズライブ",
        "date_str": "2026年9月12日(土) 17:00〜20:30",
        "location": "蓮華寺池公園 野外音楽堂周辺",
        "city": "藤枝市",
        "address": "静岡県藤枝市若王子1-455-1",
        "lat": 34.8723,
        "lng": 138.2567,
        "google_maps_url": "https://maps.google.com/?q=34.8723,138.2567",
        "official_url": "https://www.city.fujieda.shizuoka.jp/",
        "tags": "蓮華寺池公園, 今週末, ジャズライブ, ピクニック, 竹あかり",
        "summary": "池のほとりで心地よいジャズに酔いしれる秋夜。キッチンカーや竹あかりの点灯も。",
        "description": "藤枝市民の憩いの場・蓮華寺池公園で開催される水辺のナイトイベント。池を彩る竹あかりの幻想的な光の中で、地元ミュージシャンによる本格的なジャズ演奏をレジャーシートを広げて楽しめます。",
        "image_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
        "fee": "観覧無料",
        "organizer": "藤枝市賑わい創出課",
        "parking_info": "蓮華寺池公園第1・第2無料駐車場あり",
        "target_age": "大人・カップル・ファミリー",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "修善寺温泉 竹林の小径 秋の観月会 2026",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 18:30〜21:00",
        "location": "修善寺温泉 竹林の小径",
        "city": "伊豆市",
        "address": "静岡県伊豆市修善寺",
        "lat": 34.9723,
        "lng": 138.9245,
        "google_maps_url": "https://maps.google.com/?q=34.9723,138.9245",
        "official_url": "https://www.shuzenji-kankou.com/",
        "tags": "修善寺温泉, 今週末, 観月会, 竹林, 箏曲演奏",
        "summary": "ライトアップされた竹林で澄んだ秋月を愛でる。和箏の美しい調べが響く風情豊かな夜。",
        "description": "伊豆最古の修善寺温泉で開催される観月イベント。竹林の円形ベンチ周辺にて、地元の演者による和箏や尺八の演奏会が開催されます。温泉街の旅館宿泊者や散策客に大好評の風流な催しです。",
        "image_url": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
        "fee": "鑑賞無料",
        "organizer": "修善寺温泉旅館協同組合",
        "parking_info": "温泉街有料駐車場ご利用",
        "target_age": "大人・カップル推奨",
        "is_free_parking": 0,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け"
    },
    {
        "item_type": "event",
        "title": "富士川楽座 富士山パンフェスティバル 2026",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 10:00〜15:30",
        "location": "道の駅 富士川楽座 3階屋外広場",
        "city": "富士市",
        "address": "静岡県富士市岩淵1488-1",
        "lat": 35.1589,
        "lng": 138.6189,
        "google_maps_url": "https://maps.google.com/?q=35.1589,138.6189",
        "official_url": "https://www.fujikawarakuza.co.jp/",
        "tags": "パンフェス, 今週末, 富士川楽座, 富士山 view, 屋内屋外",
        "summary": "静岡・山梨の人気ベーカリー25店が勢揃い！富士山を望む道の駅で開催されるパンの祭典。",
        "description": "東名富士川SA併設の道の駅「富士川楽座」で開催される大人気パンフェス。限定カレーパン、生食パン、フルーツサンドなど話題のベーカリーが一堂に会します。館内は全天候型で雨でも楽しめます。",
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "富士川楽座",
        "parking_info": "大型無料駐車場完備",
        "target_age": "全年齢（ファミリー大人気）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "ファミリー向け,雨の日OK,カップル向け"
    },
    {
        "item_type": "event",
        "title": "袋井可睡斎 秋の精進料理体験＆風涼まいり",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 9:00〜16:30",
        "location": "遠州三山 遠州可睡斎",
        "city": "袋井市",
        "address": "静岡県袋井市久能2915-1",
        "lat": 34.7645,
        "lng": 137.9234,
        "google_maps_url": "https://maps.google.com/?q=34.7645,137.9234",
        "official_url": "https://www.kasuisai.or.jp/",
        "tags": "可睡斎, 今週末, 精進料理, 禅体験, 風鈴",
        "summary": "徳川家康ゆかりの古刹で味わう本格精進料理と、境内に飾られた風鈴の音色を楽しむ週末。",
        "description": "遠州の名刹・可睡斎で開催される特別体験イベント。修行僧が心を込めて作る伝統の精進料理（要事前問い合わせ/当日空きあれば受付）を味わえるほか、写経・座禅体験や秋風にそよぐ風鈴小道散策を楽しめます。",
        "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
        "fee": "境内散策無料",
        "organizer": "可睡斎",
        "parking_info": "参道無料駐車場あり",
        "target_age": "全年齢（シニア・カップル）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "カップル向け,雨の日OK,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "浜名湖ガーデンパーク 秋の花まつり＆クラフト体験",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 9:30〜16:30",
        "location": "浜名湖ガーデンパーク 展望塔広場",
        "city": "浜松市",
        "address": "静岡県浜松市中央区村櫛町5475-1",
        "lat": 34.7123,
        "lng": 137.6012,
        "google_maps_url": "https://maps.google.com/?q=34.7123,137.6012",
        "official_url": "https://www.hamanako-gardenpark.jp/",
        "tags": "浜名湖ガーデンパーク, 今週末, コスモス, ガーデニング",
        "summary": "秋風そよぐ浜名湖畔で早咲きコスモスとガーデニング体験！入園料・駐車場ともに無料。",
        "description": "浜名湖畔の広大な公園で開催される秋の開園フェスタ。色とりどりの早咲きコスモス畑が広がり、花の寄せ植え教室やハーブ石鹸作りクラフト体験が開催されます。遊覧船「ガーデンクルーズ」も運行中。",
        "image_url": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
        "fee": "入園無料",
        "organizer": "浜名湖ガーデンパーク管理事務所",
        "parking_info": "広大無料駐車場 1,800台完備",
        "target_age": "全年齢（ファミリー・ベビーカー可）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "ファミリー向け,カップル向け"
    },
    {
        "item_type": "event",
        "title": "裾野市民公園 富士山ビューアウトドア＆テントフェス",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 10:00〜16:00",
        "location": "裾野市中央公園・運動公園広場",
        "city": "裾野市",
        "address": "静岡県裾野市千福7-1",
        "lat": 35.1789,
        "lng": 138.9012,
        "google_maps_url": "https://maps.google.com/?q=35.1789,138.9012",
        "official_url": "https://www.city.susono.shizuoka.jp/",
        "tags": "裾野, 今週末, アウトドア, 富士山, キャンプ体験",
        "summary": "富士山を目の前に最新アウトドアギアの展示・体験！薪割りやファイヤースターター体験も。",
        "description": "富士山の絶景が広がる裾野市の公園で開催されるアウトドア体験イベント。最新テントの展示、スラックラインやブッシュクラフト体験、キャンプ飯の試食ブースなどアウトドア好き必見のコンテンツ盛りだくさん。",
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "裾野市観光協会",
        "parking_info": "公園無料駐車場あり",
        "target_age": "全年齢（ファミリー・アウトドアファン）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "下田海中水族館 秋のナイトアクアリウム探検",
        "date_str": "2026年9月12日(土) 18:00〜21:00",
        "location": "下田海中水族館",
        "city": "下田市",
        "address": "静岡県下田市3-22-31",
        "lat": 34.6689,
        "lng": 138.9512,
        "google_maps_url": "https://maps.google.com/?q=34.6689,138.9512",
        "official_url": "https://shimoda-aquarium.org/",
        "tags": "下田, 今週末, 水族館, ナイト水族館, 探検, 雨の日OK",
        "summary": "夜の水族館で魚たちの眠る姿を観察！ライトアップされた大水槽と夜のイルカショーは幻想的。",
        "description": "自然の海に浮かぶ下田海中水族館で今週末土曜日限定で開催されるナイト営業。普段は見ることのできない夜の海の生き物の生態観察や、月明かりの下で行われる特別ナイトイルカショーをお楽しみいただけます。",
        "image_url": "https://images.unsplash.com/photo-1567168544813-cc03465b4fa8?auto=format&fit=crop&w=800&q=80",
        "fee": "大人 2,100円 / 小学生 1,050円",
        "organizer": "下田海中水族館",
        "parking_info": "専用無料駐車場 200台あり",
        "target_age": "全年齢（カップル・ファミリー大人気）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "カップル向け,雨の日OK,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "島田 蓬莱橋 夕涼みあんどん祭り 2026",
        "date_str": "2026年9月12日(土) 17:30〜20:30",
        "location": "世界一長い木造歩道橋「蓬莱橋」",
        "city": "島田市",
        "address": "静岡県島田市南2-22-14",
        "lat": 34.8278,
        "lng": 138.1812,
        "google_maps_url": "https://maps.google.com/?q=34.8278,138.1812",
        "official_url": "https://www.city.shimada.shizuoka.jp/",
        "tags": "蓬莱橋, 今週末, ギネス認定, あんどん, 島田",
        "summary": "897.4mの木造歩道橋に手作り行燈がズラリ。大井川の夕風を感じる和のイベント。",
        "description": "ギネス世界記録に認定された世界一長い木造歩道橋「蓬莱橋」で開催される秋の夕涼み行燈まつり。地元の子供たちが絵付けした行燈約200個が橋のたもとから対岸まで灯され、ノスタルジックな雰囲気を演出します。",
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
        "fee": "渡橋料 大人100円 / 小学生10円",
        "organizer": "島田市観光協会",
        "parking_info": "蓬莱橋897.4広場無料駐車場あり",
        "target_age": "全年齢（カップル・シニア）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 0,
        "category_scene": "カップル向け,ファミリー向け"
    },
    {
        "item_type": "event",
        "title": "御殿場プレミアム・アウトレット 秋のオータムマルシェ",
        "date_str": "2026年9月12日(土) 〜 9月13日(日) 10:00〜19:00",
        "location": "御殿場プレミアム・アウトレット HILL SIDEエリア",
        "city": "御殿場市",
        "address": "静岡県御殿場市深沢1312",
        "lat": 35.3089,
        "lng": 138.9645,
        "google_maps_url": "https://maps.google.com/?q=35.3089,138.9645",
        "official_url": "https://www.premiumoutlets.co.jp/gotemba/",
        "tags": "御殿場, 今週末, アウトレット, ショッピング, 富士山 view",
        "summary": "富士山を正面に臨む最新エリアで秋の特別マルシェ開催！ご当地スイーツや限定ショップ。",
        "description": "富士山を望む大人気の御殿場プレミアム・アウトレットで今週末開催されるオータムマルシェ。富士宮やきそば、静岡抹茶スイーツ、クラフト雑貨の限定出店が並び、ショッピングとあわせて楽しめます。全天候型通路完備。",
        "image_url": "https://images.unsplash.com/photo-1559598467-f8b76c8155d0?auto=format&fit=crop&w=800&q=80",
        "fee": "入場無料",
        "organizer": "御殿場プレミアム・アウトレット",
        "parking_info": "無料駐車場 約5,000台完備",
        "target_age": "全年齢（カップル・ファミリー）",
        "is_free_parking": 1,
        "is_stroller_ok": 1,
        "is_rainy_ok": 1,
        "category_scene": "カップル向け,雨の日OK,ファミリー向け"
    }
]

def add_weekend_events():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    count_inserted = 0
    count_updated = 0

    for item in WEEKEND_EVENTS_DATA:
        cursor.execute("SELECT id FROM events WHERE title = ?", (item["title"],))
        existing = cursor.fetchone()

        if existing:
            event_id = existing[0]
            cursor.execute("""
            UPDATE events 
            SET item_type = ?, title = ?, date_str = ?, location = ?, city = ?, address = ?, lat = ?, lng = ?, google_maps_url = ?, official_url = ?,
                tags = ?, summary = ?, description = ?, image_url = ?, fee = ?, organizer = ?,
                parking_info = ?, target_age = ?, is_free_parking = ?, is_stroller_ok = ?, is_rainy_ok = ?, category_scene = ?
            WHERE id = ?
            """, (
                item["item_type"], item["title"], item["date_str"], item["location"], item["city"], item["address"],
                item["lat"], item["lng"], item["google_maps_url"], item["official_url"], item["tags"], item["summary"],
                item["description"], item["image_url"], item["fee"], item["organizer"],
                item["parking_info"], item["target_age"], item["is_free_parking"], item["is_stroller_ok"],
                item["is_rainy_ok"], item["category_scene"], event_id
            ))
            count_updated += 1
            print(f"[UPDATE] Updated: {item['title']}")
        else:
            cursor.execute("""
            INSERT INTO events (
                item_type, title, date_str, location, city, address, lat, lng, google_maps_url, official_url,
                tags, summary, description, image_url, fee, organizer, parking_info, target_age,
                is_free_parking, is_stroller_ok, is_rainy_ok, category_scene
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                item["item_type"], item["title"], item["date_str"], item["location"], item["city"], item["address"],
                item["lat"], item["lng"], item["google_maps_url"], item["official_url"], item["tags"], item["summary"],
                item["description"], item["image_url"], item["fee"], item["organizer"],
                item["parking_info"], item["target_age"], item["is_free_parking"], item["is_stroller_ok"],
                item["is_rainy_ok"], item["category_scene"]
            ))
            count_inserted += 1
            print(f"[INSERT] Inserted: {item['title']}")

    conn.commit()
    conn.close()

    print(f"=== 20件の今週末イベントに official_url を設定しました (新規: {count_inserted}件, 更新: {count_updated}件) ===")

if __name__ == "__main__":
    add_weekend_events()
